export const ALL_PROGRAM_QUERY_KEY = 'ALL_PROGRAM';
export const DETAIL_PROGRAM_QUERY_KEY = 'DETAIL_PROGRAM';
export const ACCOUNT_QUERY_KEY = 'ACCOUNT';

export const TYPE_MUSTAHIQ = 10;
export const TYPE_MUZAKI = 11;
